title: Los Muertos
theme: dark 
color: zinc
favicon: images/icons/smo_favicon_color.png


layout:
  Homelab:
    style: row
    columns: 4
  Media:
    style: row
    columns: 4


providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey